import localFont from "next/font/local";
import "./globals.css";
import AuthProvider from "@/components/AuthProvider";
import CustomNavbar from "@/components/CustomNavbar";
import logo from "@/assets/images/logo.png";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <CustomNavbar logoSrc={logo} />
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
